// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ0cyj9YonEP8xrLIZfC5MbxkVvrcR86k',
    appId: '1:312829266738:web:d6bb664b32e358b23f652b',
    messagingSenderId: '312829266738',
    projectId: 'fir-tester-d3fbf',
    authDomain: 'fir-tester-d3fbf.firebaseapp.com',
    storageBucket: 'fir-tester-d3fbf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLeQ0SvKMe-SDrmHTrMlTISmoI_04H_No',
    appId: '1:312829266738:android:a42851cfb447211b3f652b',
    messagingSenderId: '312829266738',
    projectId: 'fir-tester-d3fbf',
    storageBucket: 'fir-tester-d3fbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmebz9NwlR2bYYjahvEDiqUUF6imtcLjI',
    appId: '1:312829266738:ios:c13fa94ff4d9b5db3f652b',
    messagingSenderId: '312829266738',
    projectId: 'fir-tester-d3fbf',
    storageBucket: 'fir-tester-d3fbf.appspot.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmebz9NwlR2bYYjahvEDiqUUF6imtcLjI',
    appId: '1:312829266738:ios:5acc69d1e9dcd8663f652b',
    messagingSenderId: '312829266738',
    projectId: 'fir-tester-d3fbf',
    storageBucket: 'fir-tester-d3fbf.appspot.com',
    iosBundleId: 'com.example.firebaseExample.RunnerTests',
  );
}
